// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package primitives

type IntStringCache interface {
	Put(int, string) string
	Get(int) (string, error)
}
